version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cie
      POSTGRES_PASSWORD: cie
      POSTGRES_DB: cie
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      PORT: 4000
      DATABASE_URL: postgres://cie:cie@postgres:5432/cie
      REDIS_URL: redis://redis:6379
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio12345
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - '4000:4000'

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - api
    ports:
      - '3000:3000'

volumes:
  pgdata: {}
  minio: {}

